"""fix_updated_at_default

Revision ID: bdf61a6287c9
Revises: c0ccf3f9f4e0
Create Date: 2026-09-29 11:06:00.495968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf61a6287c9'
down_revision: Union[str, Sequence[str], None] = 'c0ccf3f9f4e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column('clusters', 'updated_at', server_default=sa.text('now()'), nullable=True)
    op.alter_column('investigations', 'updated_at', server_default=sa.text('now()'), nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
