"""initial_schema

Revision ID: c0ccf3f9f4e0
Revises: 
Create Date: 2026-09-29 11:03:20.575011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ccf3f9f4e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('median_time', sa.Integer(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_hash'), 'blocks', ['hash'], unique=True)
    op.create_index(op.f('ix_blocks_height'), 'blocks', ['height'], unique=True)
    op.create_index(op.f('ix_blocks_timestamp'), 'blocks', ['timestamp'], unique=False)
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cluster_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heuristic_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('heuristic_name', sa.String(length=100), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heuristic_findings_analysis_id'), 'heuristic_findings', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_heuristic_findings_heuristic_name'), 'heuristic_findings', ['heuristic_name'], unique=False)
    op.create_index(op.f('ix_heuristic_findings_subject_id'), 'heuristic_findings', ['subject_id'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('root_subject_type', sa.String(length=50), nullable=False),
    sa.Column('root_subject_id', sa.String(length=100), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=False),
    sa.Column('snapshot_height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=False),
    sa.Column('address_type', sa.String(length=50), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('total_received_sats', sa.BigInteger(), nullable=False),
    sa.Column('total_spent_sats', sa.BigInteger(), nullable=False),
    sa.Column('current_balance_sats', sa.BigInteger(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_address'), 'addresses', ['address'], unique=True)
    op.create_index(op.f('ix_addresses_cluster_id'), 'addresses', ['cluster_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txid', sa.String(length=64), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('block_height', sa.Integer(), nullable=False),
    sa.Column('block_hash', sa.String(length=64), nullable=False),
    sa.Column('block_time', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('vsize', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('locktime', sa.Integer(), nullable=False),
    sa.Column('input_count', sa.Integer(), nullable=False),
    sa.Column('output_count', sa.Integer(), nullable=False),
    sa.Column('total_input_sats', sa.BigInteger(), nullable=False),
    sa.Column('total_output_sats', sa.BigInteger(), nullable=False),
    sa.Column('fee_sats', sa.BigInteger(), nullable=False),
    sa.Column('fee_rate', sa.Float(), nullable=False),
    sa.Column('raw_transaction_hash', sa.String(length=64), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_block_height'), 'transactions', ['block_height'], unique=False)
    op.create_index(op.f('ix_transactions_block_id'), 'transactions', ['block_id'], unique=False)
    op.create_index(op.f('ix_transactions_block_time'), 'transactions', ['block_time'], unique=False)
    op.create_index(op.f('ix_transactions_fee_rate'), 'transactions', ['fee_rate'], unique=False)
    op.create_index(op.f('ix_transactions_fee_sats'), 'transactions', ['fee_sats'], unique=False)
    op.create_index(op.f('ix_transactions_input_count'), 'transactions', ['input_count'], unique=False)
    op.create_index(op.f('ix_transactions_output_count'), 'transactions', ['output_count'], unique=False)
    op.create_index(op.f('ix_transactions_txid'), 'transactions', ['txid'], unique=True)
    op.create_index(op.f('ix_transactions_vsize'), 'transactions', ['vsize'], unique=False)
    op.create_index(op.f('ix_transactions_weight'), 'transactions', ['weight'], unique=False)
    op.create_table('inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('previous_txid', sa.String(length=64), nullable=True),
    sa.Column('previous_output_index', sa.Integer(), nullable=True),
    sa.Column('previous_value_sats', sa.BigInteger(), nullable=True),
    sa.Column('previous_script_pubkey', sa.Text(), nullable=True),
    sa.Column('previous_address', sa.String(length=255), nullable=True),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('is_coinbase', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inputs_previous_address'), 'inputs', ['previous_address'], unique=False)
    op.create_index(op.f('ix_inputs_previous_txid'), 'inputs', ['previous_txid'], unique=False)
    op.create_index(op.f('ix_inputs_transaction_id'), 'inputs', ['transaction_id'], unique=False)
    op.create_table('outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('output_index', sa.Integer(), nullable=False),
    sa.Column('value_sats', sa.BigInteger(), nullable=False),
    sa.Column('script_pubkey', sa.Text(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('script_type', sa.String(length=50), nullable=True),
    sa.Column('spent', sa.Boolean(), nullable=False),
    sa.Column('spent_by_txid', sa.String(length=64), nullable=True),
    sa.Column('spent_by_input_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outputs_address'), 'outputs', ['address'], unique=False)
    op.create_index(op.f('ix_outputs_spent'), 'outputs', ['spent'], unique=False)
    op.create_index(op.f('ix_outputs_spent_by_txid'), 'outputs', ['spent_by_txid'], unique=False)
    op.create_index(op.f('ix_outputs_transaction_id'), 'outputs', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outputs_transaction_id'), table_name='outputs')
    op.drop_index(op.f('ix_outputs_spent_by_txid'), table_name='outputs')
    op.drop_index(op.f('ix_outputs_spent'), table_name='outputs')
    op.drop_index(op.f('ix_outputs_address'), table_name='outputs')
    op.drop_table('outputs')
    op.drop_index(op.f('ix_inputs_transaction_id'), table_name='inputs')
    op.drop_index(op.f('ix_inputs_previous_txid'), table_name='inputs')
    op.drop_index(op.f('ix_inputs_previous_address'), table_name='inputs')
    op.drop_table('inputs')
    op.drop_index(op.f('ix_transactions_weight'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_vsize'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_txid'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_output_count'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_input_count'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_fee_sats'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_fee_rate'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_block_time'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_block_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_block_height'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_addresses_cluster_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_address'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_heuristic_findings_subject_id'), table_name='heuristic_findings')
    op.drop_index(op.f('ix_heuristic_findings_heuristic_name'), table_name='heuristic_findings')
    op.drop_index(op.f('ix_heuristic_findings_analysis_id'), table_name='heuristic_findings')
    op.drop_table('heuristic_findings')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_blocks_timestamp'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_height'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_hash'), table_name='blocks')
    op.drop_table('blocks')
    # ### end Alembic commands ###
